spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.26.129:9300 #配置java访问elasticsearch端口
      client:
        reactive:
          connection-timeout: 1200
      cluster-name: my-application